# Generated by Django 3.2.7 on 2021-10-19 05:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, verbose_name='UserName')),
                ('user_password', models.CharField(max_length=64, verbose_name='Password')),
                ('user_email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('user_photo', models.ImageField(upload_to='User/profile_photo', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Profile-photo')),
                ('user_age', models.PositiveIntegerField(verbose_name='Age')),
                ('user_gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('user_contact', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.PositiveIntegerField(verbose_name='Order-No')),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='Product-qty')),
                ('total', models.PositiveIntegerField(verbose_name='Total-Amount')),
                ('address', models.TextField(verbose_name='Address')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Payment-Method')),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Approved'), ('2', 'Dispatched'), ('3', 'Delievered'), ('4', 'Cancelled')], max_length=50, verbose_name='status')),
                ('ordered_date', models.DateField(auto_now_add=True, verbose_name='Ordered-Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.products', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveIntegerField(default=1, verbose_name='product_qty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('product_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.products', verbose_name='Product-item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pin_code', models.PositiveIntegerField(verbose_name='Pincode')),
                ('postal_address', models.TextField(verbose_name='Postal Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
    ]
